config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show]
  resources :artists, only: [:index, :show, :update] do
    collection do
      get :discover
    end
    member do
      post :follow
      post :unfollow
    end

  end
  resources :contents, only: [:index, :show]
  get '/posts' => "posts#index", :as => :user_root
  get '/profile' => "pages#profile"
end

app/views/shared/_animated_logo.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve" height="64" width="64">
  <circle cx="50" cy="50" r="37.9">
    <animate id="second" begin="3s" attributeType="XML" attributeName="fill" to="white" dur="1s" fill="freeze"></animate>
  </circle>
  <path d="M50,5
           C25.1,5,5,25.1,5,50s20.1,45,45,45s45-20.1,45-45
           S74.9,5,50,5z
           M84.7,51.6c0,1.1-0.9,2-2,2h-5.4
           c-0.9,0-1.6-0.6-1.9-1.4l0-0.1l-3.1,17.5c-0.2,1-1,1.7-2,1.6c-1,0-1.8-0.7-2-1.7l-4-24.7l-3.2,16.8c-0.2,0.9-1,1.6-1.9,1.6
           c-0.9,0-1.8-0.6-2-1.5l-2.9-11l-4.9,26c-0.2,0.9-1,1.6-2,1.6c0,0-0.1,0-0.1,0c-1,0-1.8-0.8-1.9-1.8l-4-36.7l-4,28.7
           c-0.1,1-1,1.7-2,1.7c-1,0-1.8-0.8-2-1.8l-2.3-20
           L29,58.6c-0.2,0.9-1.1,1.6-2,1.6c-1,0-1.8-0.7-1.9-1.7l-1.1-6.5l-0.1,0.3
           c-0.3,0.7-1,1.2-1.8,1.2h-4.6c-1.1,0-2-0.9-2-2s0.9-2,2-2h3.3l2.3-5.2c0.4-0.8,1.2-1.3,2.1-1.2c0.9,0.1,1.6,0.8,1.7,1.6l0.5,2.8
           l2.6-12.1c0.2-1,1.1-1.6,2.1-1.6c1,0,1.8,0.8,1.9,1.8l1.9,16.5l4-28.9c0.1-1,1-1.7,2-1.7c0,0,0,0,0,0c1,0,1.8,0.8,2,1.8l4.3,39.3
           L52,41.3c0.2-0.9,1-1.6,1.9-1.6c0.9,0,1.8,0.6,2,1.5l2.9,11l3.7-19.3c0.2-0.9,1-1.6,2-1.6c0,0,0,0,0,0c1,0,1.8,0.7,1.9,1.7l3.9,24.4
           l2.5-13.8c0.2-0.9,0.9-1.6,1.8-1.6c0.9-0.1,1.8,0.5,2,1.4l2,6.4h3.9C83.8,49.6,84.7,50.5,84.7,51.6z"
    stroke="#fff" stroke-width="1" stroke-dasharray="1000" stroke-dashoffset="1000">
      <animate id="first" attributeType="XML" attributeName="stroke-dashoffset" to="0" dur="5s"></animate>
      <animate id="third" begin="3s" attributeType="XML" attributeName="stroke-width" to="0" dur="3s"></animate>
    </path>
</svg>

app/views/shared/_artist_card.html.erb
<div class="universal-card" data-artist="<%= artist.id %>">
    <div class="artist-card">
      <% if artist.photo.attached? %>
        <%= link_to artist_path(artist.id) do %>
        <%= cl_image_tag artist.photo.key %>
        <% end %>
      <% end %>
      <div class="artist-card-content">
        <div style="width: 170px; margin: 0px auto;">
          <h3 class="artist-card-text"><%= artist.name %></h3>
          <p><%= artist.followers.to_s(:delimited) %> Followers</p>
        </div>
        <% if current_user.is_following?(artist.id) %>
          <%= link_to "UNFOLLOW", unfollow_artist_path(artist.id), method: :post, remote: true, :class => "btn-follow" %>
        <% else %>
          <%= link_to "FOLLOW", follow_artist_path(artist.id), method: :post, remote: true, :class => "btn-follow"%>
        <% end %>
      </div>
    </div>
</div>

app/views/shared/_discover_card.html.erb
<div class="universal-card" data-artist="<%= artist.id %>">
    <div class="artist-card">
      <% if artist.photo.attached? %>
        <%= link_to artist_path(artist.id) do %>
        <%= cl_image_tag artist.photo.key %>
        <% end %>
      <% end %>
      <div class="artist-card-content">
        <div style="width: 170px; margin: 0px auto;">
          <h3 class="artist-card-text"><%= artist.name %></h3>
          <p><%= artist.followers.to_s(:delimited) %> Followers</p>
        </div>
        <% if current_user.is_following?(artist.id) %>
          <%= link_to "UNFOLLOW", unfollow_artist_path(artist.id), method: :post, remote: true, :class => "btn-follow" %>
        <% else %>
          <%= link_to "FOLLOW", follow_artist_path(artist.id), method: :post, remote: true, :class => "btn-follow"%>
        <% end %>
      </div>
    </div>
</div>

app/views/shared/_facebook_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <% end %>
    <div>
      <h3><%= post.artist.name %> posted on <span style="color:#4267B2"><%= post.source %></span></h3>
      <% if post.contents %>
        <% post.contents.each do |content| %>
          <p><%= content.data if content.format == 'text' %></p>
        <% end %>
    <% end %>
    </div>
  </div>
  <% if post.contents %>
    <% post.contents.each do |content| %>
      <% if content.format == 'image' %>
        <%= cl_image_tag content.data, class: "universal-image" %>
      <% end %>
    <% end %>
  <% end %>
  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>

app/views/shared/_feed_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <h3><%= post.artist.name %> posted on <span style="color:#1777f2"><%= post.source %></span></h3>
    <% end %>
  </div>
  <% if post.contents %>
    <% post.contents.each do |content| %>
      <p><%= content.data if content.format == 'text' %></p>
      <% if content.format == 'image' %>
        <%= cl_image_tag content.data, class: "universal-image" %>
      <% end %>
    <% end %>
  <% end %>


  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-logo">
    <%= render 'shared/logo' %>
  </div>
  <div class="header-user-avatar">
    <%= link_to profile_path(current_user) do %>
      <%= cl_image_tag 'https://res.cloudinary.com/dtdxhxnyd/image/upload/v1602430168/dy1broo66bxwa4soe6so.jpg' %>
    <% end %>
  </div>
</div>

app/views/shared/_instagram_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <% end %>
    <div>
      <h3><%= post.artist.name %> posted on <span style="color:#e1306c"><%= post.source %></span></h3>
      <% if post.contents %>
        <% post.contents.each do |content| %>
          <p><%= content.data if content.format == 'text' %></p>
        <% end %>
    <% end %>
    </div>
  </div>
  <% if post.contents %>
    <% post.contents.each do |content| %>
      <% if content.format == 'image' %>
        <%= cl_image_tag content.data, class: "universal-image" %>
      <% end %>
    <% end %>
  <% end %>
  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notification_badge.html.erb
<%= link_to posts_path(@post), class: "notification-badge" do %>
    <%= current_user.notifications.unread.count %>
<% end %>

app/views/shared/_songkick_card.html.erb
<div class="universal-card songkick-card">
  <div class="post-title">
    <% if post.artist.photo %>
        <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class:"feed-avatar" %>
        <% end %>
      <% end %>
      <div class="songkick-title">
      <div>
        <h3> <%= post.artist.name %> has a new concert on <span style="color:#FF004E"> <%= post.source %></span></h3>
        <p><%= post.contents.first.data %></p>
      </div>
      <div class="btn-buy-tickets"> VIEW EVENT</div>
      </div>
  </div>
    <div class="card-share">
      <i class="fal fa-retweet"></i>
      <i class="fal fa-heart"></i>
    </div>
</div>

app/views/shared/_soundcloud_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <% end %>
    <h3><%= post.artist.name %> posted on <span style="color:#ff4200"><%= post.source %></span></h3>
  </div>
  <% if post.contents %>
    <iframe style="margin-top: 8px;" width="100%" height="179" scrolling="no" frameborder="no" allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= post.contents[0].data %>&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=false&visual=true">
    </iframe>
  <% end %>
  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>

app/views/shared/_twitter_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <% end %>
    <div>
      <h3><%= post.artist.name %> posted on <span style="color:#1da1f2"><%= post.source %></span></h3>
      <% if post.contents %>
        <% post.contents.each do |content| %>
          <p><%= content.data if content.format == 'text' %></p>
        <% end %>
    <% end %>
    </div>
  </div>
  <% if post.contents %>
    <% post.contents.each do |content| %>
      <% if content.format == 'image' %>
        <%= cl_image_tag content.data, class: "universal-image" %>
      <% end %>
    <% end %>
  <% end %>
  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>

app/views/shared/_youtube_card.html.erb
<div class="universal-card feed-card">
  <div class="post-title">
    <% if post.artist.photo %>
      <%= link_to artist_path(post.artist) do %>
        <%= cl_image_tag post.artist.photo.key, class: "feed-avatar"%>
      <% end %>
    <h3><%= post.artist.name %> posted on <span style="color:#FF0000"><%= post.source %></span></h3>
    <% end %>
  </div>
  <% if post.contents %>
      <iframe style="margin-top: 8px;" width="318" height="179" src="https://<%= post.contents[0].data %>" frameborder="0" allowfullscreen></iframe>
  <% end %>
  <div class="card-share">
    <i class="fal fa-retweet"></i>
    <i class="fal fa-heart"></i>
  </div>
</div>